// Code generated by generate-validators; DO NOT EDIT.

// Package markers defines all markers used in the govalid package.
package markers

var (
	// GoValidMarkerCel is the marker for cel validation.
	GoValidMarkerCel = "govalid:cel"

	// GoValidMarkerEmail is the marker for email validation.
	GoValidMarkerEmail = "govalid:email"

	// GoValidMarkerEnum is the marker for enum validation.
	GoValidMarkerEnum = "govalid:enum"

	// GoValidMarkerGt is the marker for gt validation.
	GoValidMarkerGt = "govalid:gt"

	// GoValidMarkerGte is the marker for gte validation.
	GoValidMarkerGte = "govalid:gte"

	// GoValidMarkerLt is the marker for lt validation.
	GoValidMarkerLt = "govalid:lt"

	// GoValidMarkerLte is the marker for lte validation.
	GoValidMarkerLte = "govalid:lte"

	// GoValidMarkerMaxitems is the marker for maxitems validation.
	GoValidMarkerMaxitems = "govalid:maxitems"

	// GoValidMarkerMaxlength is the marker for maxlength validation.
	GoValidMarkerMaxlength = "govalid:maxlength"

	// GoValidMarkerMinitems is the marker for minitems validation.
	GoValidMarkerMinitems = "govalid:minitems"

	// GoValidMarkerMinlength is the marker for minlength validation.
	GoValidMarkerMinlength = "govalid:minlength"

	// GoValidMarkerRequired is the marker for required validation.
	GoValidMarkerRequired = "govalid:required"

	// GoValidMarkerUrl is the marker for url validation.
	GoValidMarkerUrl = "govalid:url"

	// GoValidMarkerUuid is the marker for uuid validation.
	GoValidMarkerUuid = "govalid:uuid"

)

// GoValidMarkers is a map of valid govalid markers.
var GoValidMarkers = map[string]struct{}{
	GoValidMarkerCel: {},
	GoValidMarkerEmail: {},
	GoValidMarkerEnum: {},
	GoValidMarkerGt: {},
	GoValidMarkerGte: {},
	GoValidMarkerLt: {},
	GoValidMarkerLte: {},
	GoValidMarkerMaxitems: {},
	GoValidMarkerMaxlength: {},
	GoValidMarkerMinitems: {},
	GoValidMarkerMinlength: {},
	GoValidMarkerRequired: {},
	GoValidMarkerUrl: {},
	GoValidMarkerUuid: {},
}