// Code generated by generate-validators; DO NOT EDIT.

// Package markers defines all markers used in the govalid package.
package markers

var (
	// GoValidMarkerCEL is the marker for CEL (Common Expression Language) validation in govalid.
	// This marker is only available for all types.
	GoValidMarkerCEL = "govalid:cel"

	// GoValidMarkerEmail is the marker for checking if a string is a valid email address in govalid.
	// This marker is only available for string types.
	GoValidMarkerEmail = "govalid:email"

	// GoValidMarkerEnum is the marker for checking if a field value is within a specified set of allowed values in govalid.
	// This marker is only available for string, numeric, and custom types with comparable values.
	GoValidMarkerEnum = "govalid:enum"

	// GoValidMarkerGT is the marker for checking if a value is greater than a specified minimum in govalid.
	// This marker is only available for numeric types.
	GoValidMarkerGT = "govalid:gt"

	// GoValidMarkerGTE is the marker for checking if a value is greater than or equal to a specified minimum in govalid.
	// This marker is only available for numeric types.
	GoValidMarkerGTE = "govalid:gte"

	// GoValidMarkerLT is the marker for checking if a value is less than a specified maximum in govalid.
	// This marker is only available for numeric types.
	GoValidMarkerLT = "govalid:lt"

	// GoValidMarkerLTE is the marker for checking if a value is less than or equal to a specified maximum in govalid.
	// This marker is only available for numeric types.
	GoValidMarkerLTE = "govalid:lte"

	// GoValidMarkerMaxItems is the marker for checking if a collection's length is less than or equal to a specified maximum in govalid.
	// This marker is only available for slice, array, map, and channel types.
	GoValidMarkerMaxItems = "govalid:maxitems"

	// GoValidMarkerMaxLength is the marker for checking if a string's length is less than or equal to a specified maximum in govalid.
	// This marker is only available for string types.
	GoValidMarkerMaxLength = "govalid:maxlength"

	// GoValidMarkerMinItems is the marker for checking if a collection's length is greater than or equal to a specified minimum in govalid.
	// This marker is only available for slice, array, map, and channel types.
	GoValidMarkerMinItems = "govalid:minitems"

	// GoValidMarkerMinLength is the marker for checking if a string's length is greater than or equal to a specified minimum in govalid.
	// This marker is only available for string types.
	GoValidMarkerMinLength = "govalid:minlength"

	// GoValidMarkerRequired is the marker for required fields in govalid.
	GoValidMarkerRequired = "govalid:required"

	// GoValidMarkerURL is the marker for checking if a string is a valid URL in govalid.
	// This marker is only available for string types.
	GoValidMarkerURL = "govalid:url"

	// GoValidMarkerUUID is the marker for checking if a string is a valid UUID in govalid.
	// This marker is only available for string types.
	GoValidMarkerUUID = "govalid:uuid"

)

// GoValidMarkers is a map of valid govalid markers.
var GoValidMarkers = map[string]struct{}{
	GoValidMarkerCEL: {},
	GoValidMarkerEmail: {},
	GoValidMarkerEnum: {},
	GoValidMarkerGT: {},
	GoValidMarkerGTE: {},
	GoValidMarkerLT: {},
	GoValidMarkerLTE: {},
	GoValidMarkerMaxItems: {},
	GoValidMarkerMaxLength: {},
	GoValidMarkerMinItems: {},
	GoValidMarkerMinLength: {},
	GoValidMarkerRequired: {},
	GoValidMarkerURL: {},
	GoValidMarkerUUID: {},
}