// Code generated by govalid; DO NOT EDIT.
package cel

import (
	"errors"
)

var (
	// ErrNilCEL is returned when the CEL is nil.
	ErrNilCEL = errors.New("input CEL is nil")

	// ErrScoreCELValidation is the error returned when the CEL expression evaluation fails.
	ErrScoreCELValidation = errors.New("field Score failed CEL validation: value > 0.0")

	// ErrNameCELValidation is the error returned when the CEL expression evaluation fails.
	ErrNameCELValidation = errors.New("field Name failed CEL validation: size(value) > 0")
)

func ValidateCEL(t *CEL) error {
	if t == nil {
		return ErrNilCEL
	}

	if !(t.Score > 0) {
		return ErrScoreCELValidation
	}

	if !(len(t.Name) > 0) {
		return ErrNameCELValidation
	}

	return nil
}
