// Code generated by govalid; DO NOT EDIT.
package cel

import (
	"errors"
)

var (
	// ErrNilOrder is returned when the Order is nil.
	ErrNilOrder = errors.New("input Order is nil")

	// ErrPriceCELValidation is the error returned when the CEL expression evaluation fails.
	ErrPriceCELValidation = errors.New("field Price failed CEL validation: value < this.MaxPrice")
)

func ValidateOrder(t *Order) error {
	if t == nil {
		return ErrNilOrder
	}

	if !(t.Price < t.MaxPrice) {
		return ErrPriceCELValidation
	}

	return nil
}
