// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	"regexp"
)

var (
	// ErrNilURL is returned when the URL is nil.
	ErrNilURL = errors.New("input URL is nil")

	// urlRegex is the compiled regex pattern for URL validation.
	urlRegex = regexp.MustCompile("^https?://[a-zA-Z0-9.-]+[a-zA-Z0-9]+(:[0-9]+)?(/[^?\\s]*)?(\\?[^#\\s]*)?(#[^\\s]*)?$")
	// ErrURLURLValidation is the error returned when the field is not a valid URL.
	ErrURLURLValidation = errors.New("field URL must be a valid URL")
)

func ValidateURL(t *URL) error {
	if t == nil {
		return ErrNilURL
	}

	if !urlRegex.MatchString(t.URL) {
		return ErrURLURLValidation
	}

	return nil
}
