// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
)

var (
	// ErrNilCEL is returned when the CEL is nil.
	ErrNilCEL = errors.New("input CEL is nil")

	// ErrCELAgeCELValidation is the error returned when the CEL expression evaluation fails.
	ErrCELAgeCELValidation = errors.New("field CELAge failed CEL validation: value >= 18")

	// ErrCELNameCELValidation is the error returned when the CEL expression evaluation fails.
	ErrCELNameCELValidation = errors.New("field CELName failed CEL validation: size(value) > 0")

	// ErrCELScoreCELValidation is the error returned when the CEL expression evaluation fails.
	ErrCELScoreCELValidation = errors.New("field CELScore failed CEL validation: value > 0.0")

	// ErrCELIsActiveCELValidation is the error returned when the CEL expression evaluation fails.
	ErrCELIsActiveCELValidation = errors.New("field CELIsActive failed CEL validation: value == true")
)

func ValidateCEL(t *CEL) error {
	if t == nil {
		return ErrNilCEL
	}

	if !(t.Age >= 18) {
		return ErrCELAgeCELValidation
	}

	if !(len(t.Name) > 0) {
		return ErrCELNameCELValidation
	}

	if !(t.Score > 0) {
		return ErrCELScoreCELValidation
	}

	if !(t.IsActive == true) {
		return ErrCELIsActiveCELValidation
	}

	return nil
}
