// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
)

var (
	// ErrNilCELCrossField is returned when the CELCrossField is nil.
	ErrNilCELCrossField = errors.New("input CELCrossField is nil")

	// ErrPriceCELValidation is the error returned when the CEL expression evaluation fails.
	ErrPriceCELValidation = errors.New("field Price failed CEL validation: value < this.MaxPrice")

	// ErrQuantityCELValidation is the error returned when the CEL expression evaluation fails.
	ErrQuantityCELValidation = errors.New("field Quantity failed CEL validation: value * this.Price <= this.Budget")
)

func ValidateCELCrossField(t *CELCrossField) error {
	if t == nil {
		return ErrNilCELCrossField
	}

	if !(t.Price < t.MaxPrice) {
		return ErrPriceCELValidation
	}

	if !(t.Quantity*t.Price <= t.Budget) {
		return ErrQuantityCELValidation
	}

	return nil
}
