// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
)

var (
	// ErrNilCELCrossField is returned when the CELCrossField is nil.
	ErrNilCELCrossField = errors.New("input CELCrossField is nil")

	// ErrCELCrossFieldPriceCELValidation is the error returned when the CEL expression evaluation fails.
	ErrCELCrossFieldPriceCELValidation = errors.New("field CELCrossFieldPrice failed CEL validation: value < this.MaxPrice")

	// ErrCELCrossFieldQuantityCELValidation is the error returned when the CEL expression evaluation fails.
	ErrCELCrossFieldQuantityCELValidation = errors.New("field CELCrossFieldQuantity failed CEL validation: value * this.Price <= this.Budget")
)

func ValidateCELCrossField(t *CELCrossField) error {
	if t == nil {
		return ErrNilCELCrossField
	}

	if !(t.Price < t.MaxPrice) {
		return ErrCELCrossFieldPriceCELValidation
	}

	if !(t.Quantity*t.Price <= t.Budget) {
		return ErrCELCrossFieldQuantityCELValidation
	}

	return nil
}
