// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
)

var (
	// ErrNilMaxItems is returned when the MaxItems is nil.
	ErrNilMaxItems = errors.New("input MaxItems is nil")

	// ErrItemsMaxItemsValidation is the error returned when the length of the field exceeds the maximum of 5.
	ErrItemsMaxItemsValidation = errors.New("field Items must have a maximum of 5 items")
)

func ValidateMaxItems(t *MaxItems) error {
	if t == nil {
		return ErrNilMaxItems
	}

	if len(t.Items) > 5 {
		return ErrItemsMaxItemsValidation
	}

	return nil
}
