// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
)

var (
	// ErrNilGT is returned when the GT is nil.
	ErrNilGT = errors.New("input GT is nil")

	// ErrGTAgeGTValidation is the error returned when the value of the field is less than the 100.
	ErrGTAgeGTValidation = errors.New("field GTAge must be greater than 100")
)

func ValidateGT(t *GT) error {
	if t == nil {
		return ErrNilGT
	}

	if !(t.Age > 100) {
		return ErrGTAgeGTValidation
	}

	return nil
}
