// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
)

var (
	// ErrNilMaxItems is returned when the MaxItems is nil.
	ErrNilMaxItems = errors.New("input MaxItems is nil")

	// ErrMaxItemsItemsMaxItemsValidation is the error returned when the length of the field exceeds the maximum of 5.
	ErrMaxItemsItemsMaxItemsValidation = errors.New("field MaxItemsItems must have a maximum of 5 items")

	// ErrMaxItemsMetadataMaxItemsValidation is the error returned when the length of the field exceeds the maximum of 3.
	ErrMaxItemsMetadataMaxItemsValidation = errors.New("field MaxItemsMetadata must have a maximum of 3 items")

	// ErrMaxItemsChanFieldMaxItemsValidation is the error returned when the length of the field exceeds the maximum of 2.
	ErrMaxItemsChanFieldMaxItemsValidation = errors.New("field MaxItemsChanField must have a maximum of 2 items")
)

func ValidateMaxItems(t *MaxItems) error {
	if t == nil {
		return ErrNilMaxItems
	}

	if len(t.Items) > 5 {
		return ErrMaxItemsItemsMaxItemsValidation
	}

	if len(t.Metadata) > 3 {
		return ErrMaxItemsMetadataMaxItemsValidation
	}

	if len(t.ChanField) > 2 {
		return ErrMaxItemsChanFieldMaxItemsValidation
	}

	return nil
}
