// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
)

var (
	// ErrNilGTE is returned when the GTE is nil.
	ErrNilGTE = errors.New("input GTE is nil")

	// ErrAgeGTEValidation is the error returned when the value of the field is less than 18.
	ErrAgeGTEValidation = errors.New("field Age must be greater than or equal to 18")
)

func ValidateGTE(t *GTE) error {
	if t == nil {
		return ErrNilGTE
	}

	if !(t.Age >= 18) {
		return ErrAgeGTEValidation
	}

	return nil
}
