// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
)

var (
	// ErrNilMinItems is returned when the MinItems is nil.
	ErrNilMinItems = errors.New("input MinItems is nil")

	// ErrItemsMinItemsValidation is the error returned when the length of the field is less than the minimum of 2.
	ErrItemsMinItemsValidation = errors.New("field Items must have a minimum of 2 items")

	// ErrMetadataMinItemsValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrMetadataMinItemsValidation = errors.New("field Metadata must have a minimum of 1 items")

	// ErrChanFieldMinItemsValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrChanFieldMinItemsValidation = errors.New("field ChanField must have a minimum of 1 items")
)

func ValidateMinItems(t *MinItems) error {
	if t == nil {
		return ErrNilMinItems
	}

	if len(t.Items) < 2 {
		return ErrItemsMinItemsValidation
	}

	if len(t.Metadata) < 1 {
		return ErrMetadataMinItemsValidation
	}

	if len(t.ChanField) < 1 {
		return ErrChanFieldMinItemsValidation
	}

	return nil
}
