// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"

	"github.com/sivchari/govalid/validation/validationhelper"
)

var (
	// ErrNilEmail is returned when the Email is nil.
	ErrNilEmail = errors.New("input Email is nil")

	// ErrEmailEmailEmailValidation is the error returned when the field is not a valid email address.
	ErrEmailEmailEmailValidation = errors.New("field EmailEmail must be a valid email address")
)

func ValidateEmail(t *Email) error {
	if t == nil {
		return ErrNilEmail
	}

	if !validationhelper.IsValidEmail(t.Email) {
		return ErrEmailEmailEmailValidation
	}

	return nil
}
