// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
)

var (
	// ErrNilMaxLength is returned when the MaxLength is nil.
	ErrNilMaxLength = errors.New("input MaxLength is nil")

	// ErrNameMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 50.
	ErrNameMaxLengthValidation = errors.New("field Name must have a maximum length of 50")
)

func ValidateMaxLength(t *MaxLength) error {
	if t == nil {
		return ErrNilMaxLength
	}

	if len(t.Name) > 50 {
		return ErrNameMaxLengthValidation
	}

	return nil
}
