// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	"unicode/utf8"
)

var (
	// ErrNilLength is returned when the Length is nil.
	ErrNilLength = errors.New("input Length is nil")

	// ErrLengthNameLengthValidation is the error returned when the length of the field is not exactly 7.
	ErrLengthNameLengthValidation = errors.New("field LengthName must have exactly length of 7")
)

func ValidateLength(t *Length) error {
	if t == nil {
		return ErrNilLength
	}

	if utf8.RuneCountInString(t.Name) != 7 {
		return ErrLengthNameLengthValidation
	}

	return nil
}
