// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
)

var (
	// ErrNilCELCrossField is returned when the CELCrossField is nil.
	ErrNilCELCrossField = errors.New("input CELCrossField is nil")

	// ErrPriceCELValidation is the error returned when the CEL expression evaluation fails.
	ErrPriceCELValidation = errors.New("field Price failed CEL validation: value < this.MaxPrice")
)

func ValidateCELCrossField(t *CELCrossField) error {
	if t == nil {
		return ErrNilCELCrossField
	}

	if !(t.Price < t.MaxPrice) {
		return ErrPriceCELValidation
	}

	return nil
}
