// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
)

var (
	// ErrNilLT is returned when the LT is nil.
	ErrNilLT = errors.New("input LT is nil")

	// ErrLTAgeLTValidation is the error returned when the value of the field is greater than the 10.
	ErrLTAgeLTValidation = errors.New("field LTAge must be less than 10")
)

func ValidateLT(t *LT) error {
	if t == nil {
		return ErrNilLT
	}

	if !(t.Age < 10) {
		return ErrLTAgeLTValidation
	}

	return nil
}
