// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	"github.com/sivchari/govalid/validation/validationhelper"
)

var (
	// ErrNilCEL is returned when the CEL is nil.
	ErrNilCEL = errors.New("input CEL is nil")

	// ErrScoreCELValidation is the error returned when the CEL expression evaluation fails.
	ErrScoreCELValidation = errors.New("field Score failed CEL validation: value > 0.0")
)

func ValidateCEL(t *CEL) error {
	if t == nil {
		return ErrNilCEL
	}

	if !validationhelper.IsValidCEL("value > 0.0", t.Score, t) {
		return ErrScoreCELValidation
	}

	return nil
}
