// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	"unicode/utf8"
)

var (
	// ErrNilMinLength is returned when the MinLength is nil.
	ErrNilMinLength = errors.New("input MinLength is nil")

	// ErrMinLengthNameMinLengthValidation is the error returned when the length of the field is less than the minimum of 3.
	ErrMinLengthNameMinLengthValidation = errors.New("field MinLengthName must have a minimum length of 3")
)

func ValidateMinLength(t *MinLength) error {
	if t == nil {
		return ErrNilMinLength
	}

	if utf8.RuneCountInString(t.Name) < 3 {
		return ErrMinLengthNameMinLengthValidation
	}

	return nil
}
