// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	"regexp"
)

var (
	// ErrNilEmail is returned when the Email is nil.
	ErrNilEmail = errors.New("input Email is nil")

	// emailRegex is the compiled regex pattern for email validation.
	emailRegex = regexp.MustCompile("^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$")
	// ErrEmailEmailValidation is the error returned when the field is not a valid email address.
	ErrEmailEmailValidation = errors.New("field Email must be a valid email address")
)

func ValidateEmail(t *Email) error {
	if t == nil {
		return ErrNilEmail
	}

	if !emailRegex.MatchString(t.Email) {
		return ErrEmailEmailValidation
	}

	return nil
}
