// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
)

var (
	// ErrNilMinItems is returned when the MinItems is nil.
	ErrNilMinItems = errors.New("input MinItems is nil")

	// ErrMinItemsItemsMinItemsValidation is the error returned when the length of the field is less than the minimum of 2.
	ErrMinItemsItemsMinItemsValidation = errors.New("field MinItemsItems must have a minimum of 2 items")

	// ErrMinItemsMetadataMinItemsValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrMinItemsMetadataMinItemsValidation = errors.New("field MinItemsMetadata must have a minimum of 1 items")

	// ErrMinItemsChanFieldMinItemsValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrMinItemsChanFieldMinItemsValidation = errors.New("field MinItemsChanField must have a minimum of 1 items")
)

func ValidateMinItems(t *MinItems) error {
	if t == nil {
		return ErrNilMinItems
	}

	if len(t.Items) < 2 {
		return ErrMinItemsItemsMinItemsValidation
	}

	if len(t.Metadata) < 1 {
		return ErrMinItemsMetadataMinItemsValidation
	}

	if len(t.ChanField) < 1 {
		return ErrMinItemsChanFieldMinItemsValidation
	}

	return nil
}
