// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	"github.com/sivchari/govalid/validation/validationhelper"
)

var (
	// ErrNilNumeric is returned when the Numeric is nil.
	ErrNilNumeric = errors.New("input Numeric is nil")

	// ErrNumericNumberNumericValidation is the error returned when the field is not numeric.
	ErrNumericNumberNumericValidation = errors.New("field NumericNumber must be numeric")
)

func ValidateNumeric(t *Numeric) error {
	if t == nil {
		return ErrNilNumeric
	}

	if !validationhelper.IsNumeric(t.Number) {
		return ErrNumericNumberNumericValidation
	}

	return nil
}
