// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	"unicode/utf8"
)

var (
	// ErrNilMaxLength is returned when the MaxLength is nil.
	ErrNilMaxLength = errors.New("input MaxLength is nil")

	// ErrMaxLengthNameMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 50.
	ErrMaxLengthNameMaxLengthValidation = errors.New("field MaxLengthName must have a maximum length of 50")
)

func ValidateMaxLength(t *MaxLength) error {
	if t == nil {
		return ErrNilMaxLength
	}

	if utf8.RuneCountInString(t.Name) > 50 {
		return ErrMaxLengthNameMaxLengthValidation
	}

	return nil
}
