// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
)

var (
	// ErrNilRequired is returned when the Required is nil.
	ErrNilRequired = errors.New("input Required is nil")

	// ErrNameRequiredValidation is returned when the Name is required but not provided.
	ErrNameRequiredValidation = errors.New("field Name is required")

	// ErrAgeRequiredValidation is returned when the Age is required but not provided.
	ErrAgeRequiredValidation = errors.New("field Age is required")

	// ErrItemsRequiredValidation is returned when the Items is required but not provided.
	ErrItemsRequiredValidation = errors.New("field Items is required")
)

func ValidateRequired(t *Required) error {
	if t == nil {
		return ErrNilRequired
	}

	if t.Name == "" {
		return ErrNameRequiredValidation
	}

	if t.Age == 0 {
		return ErrAgeRequiredValidation
	}

	if t.Items == nil {
		return ErrItemsRequiredValidation
	}

	return nil
}
