package govalid

var tmpl = `// Code generated by govalid; DO NOT EDIT.
package {{.PackageName}}

import (
	{{if .Metadata }}
	"errors"
	{{- end -}}
)

var (
	// ErrNil{{.TypeName}} is returned when the {{.TypeName}} is nil.
	ErrNil{{.TypeName}} = errors.New("input {{.TypeName}} is nil")
{{- range .Metadata -}}
	{{- range .Validators -}}
		{{ if ne .Validate "" }}
			{{.Err}}
		{{ end -}}
	{{- end -}}
{{ end -}}
)

func Validate{{.TypeName}}(t *{{.TypeName}}) error {
	if t == nil {
	    return ErrNil{{.TypeName}}
	}

	{{ $parentVariable := "" }}
	{{ range .Metadata -}}
		{{ if ne .ParentVariable "" }}
	    	{{ $parentVariable = .ParentVariable }}
		{{ end -}}
		{{ if and (ne $parentVariable "") ( .Validators ) }}
	    	{{ "{" }}
  			t := t.{{ $parentVariable }}
		{{ end -}}
		{{ range .Validators }}
			{{ if ne .Validate "" }}
				if {{.Validate}} {
			    	return {{ .ErrVariable }}
				}
			{{ end }}
		{{ end }}
		{{ if and (ne $parentVariable "") ( .Validators ) }}
			{{ "}" }}
			{{ $parentVariable = "" }}
		{{ end -}}
	{{ end -}}

	return nil
}
`
