/*
Copyright 2025 sivchari.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package govalid

var tmpl = `// Code generated by govalid; DO NOT EDIT.
package {{.PackageName}}

import (
	{{if .Metadata }}
	"errors"
	{{- end -}}
)

var (
	// ErrNil{{.TypeName}} is returned when the {{.TypeName}} is nil.
	ErrNil{{.TypeName}} = errors.New("input {{.TypeName}} is nil")
{{- range .Metadata -}}
	{{- range .Validators -}}
		{{ if ne .Validate "" }}
			{{.Err}}
		{{ end -}}
	{{- end -}}
{{ end -}}
)

func Validate{{.TypeName}}(t *{{.TypeName}}) error {
	if t == nil {
	    return ErrNil{{.TypeName}}
	}

	{{ $parentVariable := "" }}
	{{ range .Metadata -}}
		{{ if ne .ParentVariable "" }}
	    	{{ $parentVariable = .ParentVariable }}
		{{ end -}}
		{{ if and (ne $parentVariable "") ( .Validators ) }}
	    	{{ "{" }}
  			t := t.{{ $parentVariable }}
		{{ end -}}
		{{ range .Validators }}
			{{ if ne .Validate "" }}
				if {{.Validate}} {
			    	return {{ .ErrVariable }}
				}
			{{ end }}
		{{ end }}
		{{ if and (ne $parentVariable "") ( .Validators ) }}
			{{ "}" }}
			{{ $parentVariable = "" }}
		{{ end -}}
	{{ end -}}

	return nil
}
`
