// Code generated by generate-validators; DO NOT EDIT.

// Package initializers contains all validator initializers.
package initializers

import (
	"github.com/sivchari/govalid/internal/validator/registry"
)

// All returns all built-in validator initializers.
func All() []registry.ValidatorInitializer {
	return []registry.ValidatorInitializer{
		CELInitializer{},
		EmailInitializer{},
		EnumInitializer{},
		GTInitializer{},
		GTEInitializer{},
		LTInitializer{},
		LTEInitializer{},
		MaxItemsInitializer{},
		MaxLengthInitializer{},
		MinItemsInitializer{},
		MinLengthInitializer{},
		RequiredInitializer{},
		URLInitializer{},
		UUIDInitializer{},
	}
}